version: '3.8'
services:
  db:
    image: prunsoli/ktb-19-db:1.2
    container_name: movie-db-test
    restart: always
    ports:
      - '3306:3306'
    networks:
      - app-network
  app:
    image: yohanii/ktb_backend:latest
    container_name: movie-app
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/moviedatabase?serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=qlalfqjsgh486
    networks:
      - app-network
networks:
  app-network:
    driver: bridge