version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "9100:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
    volumes:
      - prometheus-data:/prometheus
      - ~/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-data:
  prometheus-data: