version: '3.8'

services:
  movie-crawling:
    image: prunsoli/movie-crawling:2.1.1
    container_name: movie-crawling
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
      
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    ports:
      - "9100:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg