version: '3.8'

services:
  mysql:
    image: prunsoli/ktb-19-db:1.4
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - export_network
    volumes:
      - /home/ec2-user/mysql:/var/lib/mysql

  mysqld-exporter:
    image: prom/mysqld-exporter:main
    container_name: mysql_exporter
    ports:
      - "9100:9104"
    volumes:
      - /home/ec2-user/config.my-cnf:/cfg/config-my.cnf
    command:
      - "--config.my-cnf=/cfg/config-my.cnf"
    networks:
      - export_network

networks:
  export_network:
    driver: bridge